# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""Add hashed api-key value

Revision ID: a69d272a6110
Revises: 4cbba80458c2
Create Date: 2025-10-22 20:49:33.496989

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "a69d272a6110"
down_revision = "4cbba80458c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apikey", sa.Column("hashed_key", sa.String(), nullable=True))
    op.create_index(op.f("ix_apikey_hashed_key"), "apikey", ["hashed_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apikey_hashed_key"), table_name="apikey")
    op.drop_column("apikey", "hashed_key")
    # ### end Alembic commands ###
