# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


from sqlalchemy import JSON, Column, ForeignKey, ForeignKeyConstraint, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from gfmstudio.common.models import AbstractBase
from gfmstudio.fine_tuning.core import tunes
from gfmstudio.fine_tuning.schemas import TaskPurposeEnum


class Tunes(AbstractBase):
    """
    Represents a Tunes model in the database for managing tunes and their configurations.

    Attributes
    ----------
    __tablename__ : str
        Name of the table to be created
    id : str
        A unique identifier for the Tune model, generated by the `tunes.generate_tune_id` function.
    name : str
        The name of the Tune.
    description : str, optional
        A brief description of the Tune.
    task_id : UUID
        A foreign key linking the tune to the associated task in the `ft_tune_template` table.
    config : str, optional
        Configuration details of the Tune.
    dataset_id : str
        Identifier for the dataset associated with the Tune.
    base_model_id : UUID
        A foreign key linking the Tune to the base model in the `ft_base_models` table.
    mcad_id : str
        Identifier for the MCAD job related to the Tune. TODO: Change this to k8_job_id
    status : str, default="Pending"
        The current status of the Tune (e.g., Pending, In Progress, Completed).
    progress : str, optional
        Progress status of the Tune training or processing.
    metrics : str, optional
        Performance metrics of the Tune after training.
    logs : str, optional
        Logs generated during the Tune training or processing.
    tuning_config: str, optional
        Tuning config generated during the Tune training.
    latest_chkpt : str, optional
        The latest checkpoint identifier for the Tune.
    config_json : dict, optional
        JSON-formatted configuration settings for the Tune.
    model_parameters : dict, optional
        JSON-formatted Tune parameters.
    train_options : dict, optional
        JSON-formatted training options for the Tune.
    task : Tasks
        The associated task object from the `Tasks` table.
    base_model : BaseModels
        The associated base model object from the `BaseModels` table.

    Methods
    -------
    __str__()
        Returns a string representation of the tune including its id and name.
    """

    __tablename__ = "ft_tunes"

    id = Column(String, primary_key=True, unique=True, default=tunes.generate_tune_id)
    name = Column(String, nullable=False)
    description = Column(String)
    tune_template_id = Column(UUID(as_uuid=True), ForeignKey("ft_tune_template.id"))
    config = Column(String)
    dataset_id = Column(String, ForeignKey("ft_geodataset.id"))
    base_model_id = Column(UUID, ForeignKey("ft_base_models.id"))
    mcad_id = Column(String)
    status = Column(String, default="Pending")
    progress = Column(String)
    metrics = Column(String)
    logs = Column(String)
    tuning_config = Column(String)
    latest_chkpt = Column(String)
    config_json = Column(JSON)
    model_parameters = Column(JSON)
    train_options = Column(JSON)

    tune_template = relationship("TuneTemplate", lazy="joined")
    base_model = relationship("BaseModels", lazy="joined")
    dataset = relationship("GeoDataset", lazy="joined")

    __table_args__ = (
        ForeignKeyConstraint(
            ["dataset_id"], ["ft_geodataset.id"], name="fk_tunes_dataset_id"
        ),
        ForeignKeyConstraint(
            ["base_model_id"], ["ft_base_models.id"], name="fk_tunes_base_model_id"
        ),
        ForeignKeyConstraint(
            ["tune_template_id"],
            ["ft_tune_template.id"],
            name="fk_tunes_tune_template_id",
        ),
    )

    def __str__(self):
        """Generates string representation of the tune

        Returns
        -------
        str
            String representation of the tune id  and tune name
        """
        return f"Tune(id={self.id}, name={self.name})"


class TuneTemplate(AbstractBase):
    """TuneTemplate model.

    Attributes
    ----------
    __tablename__ : str
        Name of the table to be created
    id : str
        A unique identifier for the task, inherited from the AbstractBase class.
    name : str
        The name of the task.
    description : str, optional
        A brief description of the task.
    content : str, optional
        Content or details associated with the task.
    task_schema : str, optional
        The schema defining the task structure.
    model_params : dict, optional
        JSON-formatted parameters for the model associated with the task.
    extra_info : dict, optional
        JSON-formatted additional information related to the task.
    dataset_id: str, optional
        Dataset ID for the created task

    Methods
    -------
    __str__() :
        Return a string representation of the BaseModel instance, including its id and name.
    """

    __tablename__ = "ft_tune_template"

    name = Column(String, nullable=False)
    description = Column(String)
    content = Column(String)
    task_schema = Column(String)
    model_params = Column(JSON)
    extra_info = Column(JSONB)
    dataset_id = Column(String(100))
    purpose = Column(String(20), default=TaskPurposeEnum.SEGMENTATION)

    def __str__(self):
        """Generates string representation of the task

        Returns
        -------
        str
            String representation of the task id  and task name
        """
        return f"Task(id={self.id}, name={self.name})"


class BaseModels(AbstractBase):
    """Model representing base models.

    Attributes
    ----------
    __tablename__ : str
        Name of the table to be created
    id : str
        A unique identifier for the base model, inherited from the AbstractBase class.
    name : str
        The name of the base model.
    description : str, optional
        A brief description of the base model.
    checkpoint_filename : str, optional
        The filename of the model checkpoint.
    model_params : dict, optional
        JSON-formatted parameters for the base model.

    Methods
    -------
    __str__() :
        Return a string representation of the BaseModel instance, including its id and name.
    """

    __tablename__ = "ft_base_models"

    name = Column(String, nullable=False)
    description = Column(String)
    status = Column(String, default="Finished")
    checkpoint_filename = Column(String)
    model_params = Column(JSONB)

    def __str__(self):
        """Generates string representation of the BaseModel

        Returns
        -------
        str
            String representation of the BaseModel id  and BaseModel name
        """

        return f"BaseModel(id={self.id}, name={self.name})"


class GeoDataset(AbstractBase):
    """Dataset table"""

    __tablename__ = "ft_geodataset"

    id = Column(
        String, primary_key=True, unique=True, default=tunes.generate_dataset_id
    )
    dataset_name = Column(String(100), nullable=False)
    description = Column(String(1000))
    dataset_url = Column(String(1000), nullable=False)
    label_suffix = Column(String(100), nullable=False)
    training_data_suffix = Column(String(100))
    custom_bands = Column(JSON)
    data_sources = Column(JSON)
    purpose = Column(String(20))
    label_categories = Column(JSON)
    training_params = Column(JSON)
    size = Column(String(100), default="0MB")
    status = Column(String(20), default="Pending")
    error = Column(String(), default="")
    version = Column(String())
    logs = Column(String())
    onboarding_options = Column(JSON)

    def __str__(self):
        return f"dataset_name: {self.dataset_name}, dataset_id: {self.dataset_id}"

    def to_dict(self):
        return {field.name: getattr(self, field.name) for field in self.__table__.c}
