# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: 
    class_path: lightning.pytorch.loggers.mlflow.MLFlowLogger
    init_args:
      experiment_name: prithvi-eo2
      run_name: prithvi-eo2-burnscars-<prithvi-backbone>
      tracking_uri: "https://gfm-mlflow-internal-nasageospatial-dev.cash.sl.cloud9.ibm.com"
      save_dir: /working/mlflow
      # True # will use tensorboardlogger
  callbacks:
    - class_path: RichProgressBar  
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 20
        monitor: val/loss
  max_epochs: 10
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  enable_checkpointing: True
  default_root_dir: /working/

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 2
    no_label_replace: -1
    no_data_replace: 0
    constant_scale: 1.0
    dataset_bands:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
    output_bands:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
    rgb_indices:
      - 0
      - 1
      - 2
    train_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/training_data/
    train_label_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/labels/
    val_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/training_data/
    val_label_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/labels/
    test_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/training_data/
    test_label_data_root: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/labels/
    train_split: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/split_files/train_data.txt
    test_split: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/split_files/test_data.txt
    val_split: /data/geodata-36b7bf32ae6c11efad690a580a8005c0/split_files/val_data.txt
    img_grep: "*_merged.tif"
    label_grep: "*.mask.tif"
    means: 
      - 0.052501344674454685
      - 0.07818710276892571
      - 0.09527748749364956
      - 0.21442636938609524
      - 0.23594506038412516
      - 0.1707575734110789
    stds: 
      - 0.02980933467336373
      - 0.03671671799312583
      - 0.054445047276513434
      - 0.06953507438690602
      - 0.09133826565407105
      - 0.08313280812483531
    num_classes: 3
    test_transform:
      - class_path: ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask 
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v2_300 #prithvi_eo_v1_100, prithvi_eo_v2_300, prithvi_eo_v2_300_tl, prithvi_eo_v2_600, prithvi_eo_v2_600_tl
      # backbone_ckpt_path: 
      # backbone_ckpt_path: /terratorch/gfm_models/prithvi_eo_v2_600/Prithvi_EO_V2_600M.pt # TODO
      backbone_pretrained: true
      # backbone_ckpt_path: examples/Prithvi_100M.pt
      backbone_drop_path: 0.1
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      necks:
        - name: SelectIndices
          # indices: [2, 5, 8, 11] # 100M models
          indices: [5, 11, 17, 23] # 300M models
          # indices: [7, 15, 23, 31] # 600M models . These require more cuda memory
        # Different necks are available to be provided based on the task
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
      decoder: UNetDecoder
      decoder_channels: [512, 256, 128, 64]
      head_channel_list: [256]
      head_dropout: 0.1
      num_classes: 2
    loss: dice
    aux_heads:
      - name: aux_head
        decoder: FCNDecoder
        decoder_args:
          decoder_channels: 256
          decoder_in_index: -1
          decoder_num_convs: 2
          head_dropout: 0.1
    aux_loss:
      aux_head: 1.0
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    tiled_inference_parameters: 
      h_crop: 512
      h_stride: 448
      w_crop: 512
      w_stride: 448
      average_patches: True
    

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5.0e-5
    weight_decay: 0.05

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 50