# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""Add df logs key

Revision ID: 14f9c61324e7
Revises: 86e4e3e816d2
Create Date: 2025-08-27 11:33:33.475896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14f9c61324e7"
down_revision = "86e4e3e816d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ft_geodataset", sa.Column("logs", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ft_geodataset", "logs")
    # ### end Alembic commands ###
