# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""Inf- task tbl inference_id-

Revision ID: 7d8d6eda6ffb
Revises: 14f9c61324e7
Create Date: 2025-08-29 11:21:59.209716

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "7d8d6eda6ffb"
down_revision = "14f9c61324e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inf_task", "inference_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inf_task", "inference_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
