# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


"""Inf- initial migrations

Revision ID: 8060f622f741
Revises:
Create Date: 2025-07-03 11:30:25.977320

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8060f622f741"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inf_data_source",
        sa.Column("data_connector", sa.String(length=100), nullable=True),
        sa.Column("collection_id", sa.String(length=100), nullable=True),
        sa.Column("data_connector_config", sa.JSON(), nullable=True),
        sa.Column("groups", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sharable", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inf_model",
        sa.Column("internal_name", sa.String(length=63), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model_url", sa.String(), nullable=True),
        sa.Column("pipeline_steps", sa.JSON(), nullable=True),
        sa.Column("geoserver_push", sa.JSON(), nullable=True),
        sa.Column("model_input_data_spec", sa.JSON(), nullable=True),
        sa.Column("postprocessing_options", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("groups", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sharable", sa.Boolean(), nullable=True),
        sa.Column(
            "model_onboarding_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("version", sa.Float(), nullable=True),
        sa.Column("latest", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inf_inference",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("inference_config", sa.JSON(), nullable=True),
        sa.Column("geoserver_layers", sa.JSON(), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=True),
        sa.Column("queue", sa.String(length=50), nullable=True),
        sa.Column("demo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("inference_output", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["inf_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inf_task",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "pipeline_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("inference_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("inference_folder", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=True),
        sa.Column("queue", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inference_id"],
            ["inf_inference.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_table(
        "notification",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("detail_type", sa.String(length=100), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column("inference_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inference_id"],
            ["inf_inference.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_table("inf_task")
    op.drop_table("inf_inference")
    op.drop_table("inf_model")
    op.drop_table("inf_data_source")
    # ### end Alembic commands ###
