# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""FT- initial migrations

Revision ID: 86e4e3e816d2
Revises: 8060f622f741
Create Date: 2025-07-05 19:50:40.087724

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "86e4e3e816d2"
down_revision = "8060f622f741"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ft_base_models",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("checkpoint_filename", sa.String(), nullable=True),
        sa.Column(
            "model_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ft_geodataset",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("dataset_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("dataset_url", sa.String(length=1000), nullable=False),
        sa.Column("label_suffix", sa.String(length=100), nullable=False),
        sa.Column("training_data_suffix", sa.String(length=100), nullable=True),
        sa.Column("custom_bands", sa.JSON(), nullable=True),
        sa.Column("data_sources", sa.JSON(), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=True),
        sa.Column("label_categories", sa.JSON(), nullable=True),
        sa.Column("training_params", sa.JSON(), nullable=True),
        sa.Column("size", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "ft_tune_template",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("task_schema", sa.String(), nullable=True),
        sa.Column("model_params", sa.JSON(), nullable=True),
        sa.Column("extra_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dataset_id", sa.String(length=100), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ft_tunes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tune_template_id", sa.UUID(), nullable=True),
        sa.Column("config", sa.String(), nullable=True),
        sa.Column("dataset_id", sa.String(), nullable=True),
        sa.Column("base_model_id", sa.UUID(), nullable=True),
        sa.Column("mcad_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("progress", sa.String(), nullable=True),
        sa.Column("metrics", sa.String(), nullable=True),
        sa.Column("logs", sa.String(), nullable=True),
        sa.Column("tuning_config", sa.String(), nullable=True),
        sa.Column("latest_chkpt", sa.String(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=True),
        sa.Column("model_parameters", sa.JSON(), nullable=True),
        sa.Column("train_options", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_model_id"], ["ft_base_models.id"], name="fk_tunes_base_model_id"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["ft_geodataset.id"], name="fk_tunes_dataset_id"
        ),
        sa.ForeignKeyConstraint(
            ["tune_template_id"],
            ["ft_tune_template.id"],
            name="fk_tunes_tune_template_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "ft_geodataset", ["id"])
    op.create_unique_constraint(None, "ft_tunes", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ft_tunes")
    op.drop_table("ft_tune_template")
    op.drop_table("ft_geodataset")
    op.drop_table("ft_base_models")
    op.drop_constraint(None, "ft_tunes", type_="unique")
    op.drop_constraint(None, "ft_geodataset", type_="unique")
    # ### end Alembic commands ###
