# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


"""Use abstractbase class to groups

Revision ID: a616eb3c3f22
Revises: b7c8d9e0f1a2
Create Date: 2026-05-04 18:07:19.269648

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "a616eb3c3f22"
down_revision = "b7c8d9e0f1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add id column as nullable first, then populate and make it NOT NULL
    op.add_column("artifact_permissions", sa.Column("id", sa.UUID(), nullable=True))
    # Generate UUIDs for existing rows
    op.execute("UPDATE artifact_permissions SET id = gen_random_uuid() WHERE id IS NULL")
    # Now make it NOT NULL
    op.alter_column("artifact_permissions", "id", nullable=False)
    
    op.add_column(
        "artifact_permissions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "artifact_permissions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "artifact_permissions",
        sa.Column("created_by", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "artifact_permissions",
        sa.Column("updated_by", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "artifact_permissions", sa.Column("active", sa.Boolean(), nullable=True, server_default=sa.text("true"))
    )
    # Set default value for existing rows
    op.execute("UPDATE artifact_permissions SET active = true WHERE active IS NULL")
    # Now make it NOT NULL
    op.alter_column("artifact_permissions", "active", nullable=False)
    op.add_column(
        "artifact_permissions", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.drop_index(
        op.f("ix_artifact_permissions_artifact"), table_name="artifact_permissions"
    )
    op.create_index(
        op.f("ix_artifact_permissions_artifact_id"),
        "artifact_permissions",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_permissions_artifact_type"),
        "artifact_permissions",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_permissions_group_id"),
        "artifact_permissions",
        ["group_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "ft_geodataset", ["id"])
    op.create_unique_constraint(None, "ft_tunes", ["id"])
    # Add id column as nullable first, then populate and make it NOT NULL
    op.add_column("group_members", sa.Column("id", sa.UUID(), nullable=True))
    # Generate UUIDs for existing rows
    op.execute("UPDATE group_members SET id = gen_random_uuid() WHERE id IS NULL")
    # Now make it NOT NULL
    op.alter_column("group_members", "id", nullable=False)
    
    op.add_column(
        "group_members",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "group_members",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "group_members", sa.Column("created_by", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "group_members", sa.Column("updated_by", sa.String(length=100), nullable=True)
    )
    op.add_column("group_members", sa.Column("active", sa.Boolean(), nullable=True, server_default=sa.text("true")))
    # Set default value for existing rows
    op.execute("UPDATE group_members SET active = true WHERE active IS NULL")
    # Now make it NOT NULL
    op.alter_column("group_members", "active", nullable=False)
    op.add_column("group_members", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_group_members_group_id"), "group_members", ["group_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_group_member_group_user", "group_members", ["group_id", "user_email"]
    )
    op.add_column(
        "groups",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "groups", sa.Column("updated_by", sa.String(length=100), nullable=True)
    )
    op.add_column("groups", sa.Column("active", sa.Boolean(), nullable=True, server_default=sa.text("true")))
    # Set default value for existing rows
    op.execute("UPDATE groups SET active = true WHERE active IS NULL")
    # Now make it NOT NULL
    op.alter_column("groups", "active", nullable=False)
    op.add_column("groups", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.alter_column(
        "groups",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "created_by",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("groups", "deleted")
    op.drop_column("groups", "active")
    op.drop_column("groups", "updated_by")
    op.drop_column("groups", "updated_at")
    op.drop_constraint("uq_group_member_group_user", "group_members", type_="unique")
    op.drop_index(op.f("ix_group_members_group_id"), table_name="group_members")
    op.drop_column("group_members", "deleted")
    op.drop_column("group_members", "active")
    op.drop_column("group_members", "updated_by")
    op.drop_column("group_members", "created_by")
    op.drop_column("group_members", "updated_at")
    op.drop_column("group_members", "created_at")
    op.drop_column("group_members", "id")
    op.drop_constraint(None, "ft_tunes", type_="unique")
    op.drop_constraint(None, "ft_geodataset", type_="unique")
    op.drop_index(
        op.f("ix_artifact_permissions_group_id"), table_name="artifact_permissions"
    )
    op.drop_index(
        op.f("ix_artifact_permissions_artifact_type"), table_name="artifact_permissions"
    )
    op.drop_index(
        op.f("ix_artifact_permissions_artifact_id"), table_name="artifact_permissions"
    )
    op.create_index(
        op.f("ix_artifact_permissions_artifact"),
        "artifact_permissions",
        ["artifact_type", "artifact_id"],
        unique=False,
    )
    op.drop_column("artifact_permissions", "deleted")
    op.drop_column("artifact_permissions", "active")
    op.drop_column("artifact_permissions", "updated_by")
    op.drop_column("artifact_permissions", "created_by")
    op.drop_column("artifact_permissions", "updated_at")
    op.drop_column("artifact_permissions", "created_at")
    op.drop_column("artifact_permissions", "id")
    # ### end Alembic commands ###
