# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""Update to include onboarding_options

Revision ID: d7905b61e9dc
Revises: c626caf276cd
Create Date: 2025-10-01 15:19:29.897842

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "d7905b61e9dc"
down_revision = "c626caf276cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ft_geodataset", sa.Column("onboarding_options", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ft_geodataset", "onboarding_options")
    # ### end Alembic commands ###
