# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0

"""added status to BaseModels and change inference_config to JSONB

Revision ID: f6fbafa54a75
Revises: 7d8d6eda6ffb
Create Date: 2025-10-13 11:20:36.389929

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6fbafa54a75"
down_revision = "7d8d6eda6ffb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ft_base_models",
        sa.Column("status", sa.String(), server_default="Finished", nullable=True),
    )
    op.alter_column(
        "inf_inference",
        "inference_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inf_inference",
        "inference_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("ft_base_models", "status")
    # ### end Alembic commands ###
